### ISSUE TITLE
Breaking API changes for Lemmy `0.17.0`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-js-client#103]
For API client creators, and Lemmy app devs. 

In ~ 2 weeks time, ~Jan 27th, we plan to release Lemmy `0.17.0`. This release has a large number of breaking API changes, that will break clients and apps. The additions / removals new finalized API changes for this upcoming release are here:

https://github.com/LemmyNet/lemmy-js-client/compare/0.16.4...0.17.0-rc.61

You can use https://enterprise.lemmy.ml to test your clients / apps, we'll have that updated shortly in order to do a lot of testing before this release.

Feel free to ask any questions in the [#LemmyDev chat](https://matrix.to/#/!tUnhsBRCsiePXfsIGe:matrix.org), or here.

cc @Nutomic @shilangyu @makotech222 @arsen6331

**Comment by Nutomic** [comment]
This is an old issue and already resolved.
