### ISSUE TITLE
Can't signup

### ISSUE THREAD

**Issue by Airor4** [LemmyNet/lemmy-js-client#131]
![2023-06-13 11-36-19](https://github.com/LemmyNet/lemmy-js-client/assets/31018916/1e784794-f7ca-481b-b4c8-c67f0141fd32)
Websocket breaks when signing up for lemmy.world. Not 100% sure this is the correct repo to post this to so sorry if not. Tried on firefox and chrome.

**Comment by Tealk** [comment]
I have the same Problem since 0.17.4

**Comment by dessalines** [comment]
Stale issue, feel free to reopen if its still a problem.
