### ISSUE TITLE
REST/HTTP endpoints return text/html instead of application/json when fetched from the browser

### ISSUE THREAD

**Issue by silasabbott** [LemmyNet/lemmy-js-client#137]
I might be missing something totally obvious here, but whether I use the js client or directly fetch an endpoint (getting posts for example) from the test or production instances, the endpoint returns an HTML document with the correct json inside a `<pre>` tag. Is this intentional, or is this a bug? curl in the command line returns the JSON by itself as I would expect.

**Comment by diamondburned** [comment]
(The PR that I just mentioned is not related to this issue.)

Have you tried checking what the response is in the Inspector console?

**Comment by dessalines** [comment]
Stale issue, feel free to reopen if its still a problem.
