### ISSUE TITLE
Links on docs pages are broken

### ISSUE THREAD

**Issue by csm10495** [LemmyNet/lemmy-js-client#139]
Start on https://join-lemmy.org/api/interfaces/BanPerson.html#auth.

Scroll down to the properties: 

![image](https://github.com/LemmyNet/lemmy-js-client/assets/5749838/01523c99-7008-40f6-850e-816f05227d99)

Then click any of the ts links. As far as i can tell, they all yield 404s on github. Like so:

![image](https://github.com/LemmyNet/lemmy-js-client/assets/5749838/d73fa854-bf80-4f84-8da6-946aeaadf436)

example dead link: https://github.com/LemmyNet/lemmy-js-client/tree/main/src/interfaces/api/person.ts#L183

**Comment by pascaldevink** [comment]
@csm10495 Seems to be fixed now. The types moved and I think it took some time before the docs were automatically updated. Can you check?

**Comment by csm10495** [comment]
It's different now.. there appear to be no links anymore: 
![image](https://github.com/LemmyNet/lemmy-js-client/assets/5749838/d88d99d8-2bf2-43c7-a935-fe9e45a23716)
Like we have ^ but no hyperlinks on the 'defined in...' section.

**Comment by dessalines** [comment]
Stale issue, feel free to reopen if its still a problem.
