### ISSUE TITLE
`MyUserInfo` isn't even being used at all.

### ISSUE THREAD

**Issue by fishcharlie** [LemmyNet/lemmy-js-client#140]
The [`MyUserInfo`](https://github.com/LemmyNet/lemmy-js-client/blob/main/src/types/MyUserInfo.ts) interface type isn't even being used at all as far as I can tell.

Why does this type even exist?

**Comment by gkasdorf** [comment]
It's included in the GetSiteResponse https://join-lemmy.org/api/interfaces/GetSiteResponse.html
