### ISSUE TITLE
Calls to LemmyHttp.getPosts({ community_name }) returns "All" results, not community-specific results

### ISSUE THREAD

**Issue by tconroy** [LemmyNet/lemmy-js-client#151]
I'm not sure if this is purely an implementation issue on my side, or a bug. 

I am doing a `getPosts` call with the following parameters:
```
client.getPosts({
      auth: jwt,
      sort: 'New',
      limit: 50,
      community_name: 'catlady@lemmy.world' // note: the instance the user is authenticated from is different from `lemmy.world`
});
```

For some `community_name`s, I get the correct/expected payload (only posts from that community).

For others (such as the above example), I get no posts from that community. Instead, the client returns the user's "home feed" with a `type` of `All`. 

question: How to structure the query payload to ensure only the posts for a given community are returned?

**Comment by tconroy** [comment]
A few additional notes/observations:

* the community used in this example (`catlady@lemmy.world`) has 0 posts. Could that contribute to this behavior?
* the community used in this example is [discoverable on lemmy.world](https://lemmy.world/c/catlady), however I can't seem to access it from my home instance, i.e `https://lemm.ee/c/catlady@lemmy.world` returns a 404. 

Should the client be returning a 404 in this instance as well? What is the intended behavior? 🤔

**Comment by dessalines** [comment]
iirc we fixed this in the backend.

Stale issue, feel free to reopen if its still a problem.
