### ISSUE TITLE
API for Crossposting

### ISSUE THREAD

**Issue by djtech-dev** [LemmyNet/lemmy-js-client#152]
Hi, I wanted to ask how to crosspost posts between different communities, beacuse I didn't found anything in the documentation.

**Comment by Pdzly** [comment]
Because crossposting is just copy from old post => past it into new post everything

**Comment by NatoBoram** [comment]
If this is just "copy body, url, title and create new post", then there shouldn't be a `CreatePostLike` API, it just means cross-posting is not a feature of Lemmy

**Comment by dessalines** [comment]
Wrong repo, this is just the js client for what lemmy back end supports.
