### ISSUE TITLE
Large limit filter leads to JSON parse error

### ISSUE THREAD

**Issue by nick-delirium** [LemmyNet/lemmy-js-client#157]
request: `client.listCommunities`,
payload: 
```
{
    auth: "my jwt",
    type_: "Subscribed",
    limit: 999,
    page: 1,
    sort: "TopAll",
  }
```

Result: 
` [SyntaxError: JSON Parse error: Unexpected token: F]`

<img width="502" alt="image" src="https://github.com/LemmyNet/lemmy-js-client/assets/23126999/390e205f-cf50-4d9a-b079-a1c3309cb4e8">

Semi-related: is there any better way to actually pull **all** communities user is subscribed to? This endpoint just returns a community list without total/pages and I have no idea how far pagination should go (which actually causes bug on web: open `communities/listing_type/Subscribed/page/1` and click next page until you see empty screen)

**Comment by NatoBoram** [comment]
Look at `MyUserInfo`, there should be `follows`
