### ISSUE TITLE
Create post doesnt support an image

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy-js-client#165]
When you create a post via the GUI you can select an image, but the JS API does not support it currently.

In many cases this doesn't matter because a thumbnail image will be automaticly retrieved from the posted URL, but for URL's that don't provide an image, it would be nice to be able to explictly specify the thumbnail.

**Comment by dessalines** [comment]
This would need to be handled in the back-end, but also I think explicit thumbnail overwriting isn't a good idea.
