### ISSUE TITLE
Fails with native browser fetch

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy-js-client#169]
## Reproduction

```ts
const client = new LemmyHttp("https://lemmy.world", {
  fetchFunction: fetch
});
```

https://codesandbox.io/s/practical-black-82m8ln

## Expected

Should use native browser fetch

## Result

`'fetch' called on an object that does not implement interface Window.`

**Comment by dessalines** [comment]
Use `cross-fetch`
