### ISSUE TITLE
Request: Edit blocked instances

### ISSUE THREAD

**Issue by Fmstrat** [LemmyNet/lemmy-js-client#174]
The one admin task I can't do via this library is edit the defederation (blocked instance) list. Would this be a possible addition?

**Comment by Fmstrat** [comment]
> Wrong repo, and this already exists. Go to your admin settings page.

How is this the wrong place? The intent is to use the library to do this programmatically, not by hand in admin in which case the settings page is obvious.

**Comment by dessalines** [comment]
https://join-lemmy.org/api/classes/LemmyHttp.html#editSite

**Comment by Fmstrat** [comment]
> https://join-lemmy.org/api/classes/LemmyHttp.html#editSite

Oh that is perfect. Thanks!
