### ISSUE TITLE
How to get banned users from a community?

### ISSUE THREAD

**Issue by NatoBoram** [LemmyNet/lemmy-js-client#175]
I was able to find `banFromCommunity`, but I couldn't find how to get the list of banned users in a community.

Looking at `GetCommunityResponse`, there's `moderators: CommunityModeratorView[]`, but there's no `banned` field. I guess that field should be paginated, so it makes sense if it's not there.

When looking at an individual `PostView`, there's `creator_banned_from_community: boolean`, same for `CommentView` and `creator_banned_from_community: boolean`.

As for `getBannedPersons`, I guess this is site-wide and not related to any particular community.

**Comment by dessalines** [comment]
> As for getBannedPersons, I guess this is site-wide and not related to any particular community.

That's correct, there is no endpoint currently for community-specific banned users. That would need to be added to lemmy's back end.
