### ISSUE TITLE
getUnreadRegistrationApplicationCount returns bad request

### ISSUE THREAD

**Issue by ravener** [LemmyNet/lemmy-js-client#182]
I'm simply doing this:
```js
await client.getUnreadRegistrationApplicationCount({
  auth: jwt,
});
```
and it keeps throwing `Bad Request`, I am logged in as an instance Admin and the backend is running on version 0.18.4 and the version of lemmy-js-client I have installed is the latest on npm (`0.19.0-rc.8`)

using `client.listRegistrationApplications({ auth: jwt, unread_only: true })`  also seems to be giving Bad Request when there is an entry? otherwise it does successfully return empty arrays when there's nothing.

**Comment by dessalines** [comment]
Do not use RC candidates for production instances. Use the last release of lemmy-js-client, `0.18.3`
