### ISSUE TITLE
API methods should throw Error objects instead of bare strings

### ISSUE THREAD

**Issue by phiresky** [LemmyNet/lemmy-js-client#186]
Throwing bare strings is problematic since JS only attaches stack traces to real error objects. This makes it hard to debug what is going wrong since the string will bubble up without any information where it came from:

https://github.com/LemmyNet/lemmy-js-client/blob/f439a7cedafc003c6513848da7342aacb35eab7b/src/http.ts#L1364-L1375

There's resources online on why throwing non-errors is a bad idea, for example:

https://typescript-eslint.io/rules/no-throw-literal/

https://stackoverflow.com/questions/11502052/throwing-strings-instead-of-errors

my suggestion would be to create an error subclass and throw that

```ts
class LemmyApiError extends Error {
   response: // some union type of possibilities
   constructor(response) {
        super(`lemmy api: ${response}`);
        this.response = response;
   }
}
```
This would be a breaking change since return values for errors would need to be compared by `catch (e) { e.response === "couldnt_find_object" }` and not `e === "couldnt_find_object"`

**Comment by phiresky** [comment]
What I mean is the JS stack on the client side. For example, in the API tests if a post fetch throws "couldnt_find_object", the test just fails without any way to find out which post fetch failed. If you have a larger code base and don't catch the error, you'll just get "couldnt_find_object" logged to the console without any way to find out where in your code base or which fetch it came from.

But we can let this sit and see if other people complain about it. It's just been pretty annoying trying to debug some of the api tests.

**Comment by arseniy-gl** [comment]
I think it's time to close this issue

**Comment by dessalines** [comment]
Has someone made a PR for it yet?

**Comment by phiresky** [comment]
#207 fixes the core issue. i don't think it's the best way to do errors (since they are completely untyped) but still much better than before
