### ISSUE TITLE
Missing deleteImage endpoint

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy-js-client#193]
The endpoint to delete a image from the server is missing `POST pictrs\image\delete`

**Comment by dessalines** [comment]
I'm not sure its necessary? In the lemmy backend, its a GET to `/pictrs/image/delete/{token}/{filename}` , that proxies to the pictrs backend.

We have the imageUpload explicitly defined in this codebase, but not the simple pictrs image get, or the delete.
