### ISSUE TITLE
Issue with `getSite` and `auth`

### ISSUE THREAD

**Issue by tgxn** [LemmyNet/lemmy-js-client#194]
Previously, I was passing `auth` to `getSite()` in order to fetch the current user and their metadata.

It looks like the `formData` param has been removed:
https://github.com/LemmyNet/lemmy-js-client/commit/ab7af88a2b355f816e37a55e37dc7740c4328d5b#r128832008

**Is there an alternative way to pass auth in?**

example code
```js
const lemmyClient = new LemmyHttp(`https://${instanceBase}`);

const auth = await lemmyClient.login({
  username_or_email: username,
  password: password,
});

// as long aws there is a JWT in the response from login, logged in!
if (auth.jwt) {

  // this shows the `jwt` is present 👍
  console.log("auth", auth);

  // i tried this too, but didn't seem to work :/
  lemmyClient.setHeaders({
    Cookie:	`jwt=${auth.jwt}`
  });

  // this no longer has any params
  const getSite = await lemmyClient.getSite({
    auth: auth.jwt,
  });

  // but never any user data here :(
  console.log("getSite", getSite);
}   
```

_Edit: forgot to mention, this was after upgrading to `0.19.0-rc.13` from `0.18.1`_

**Comment by tgxn** [comment]
I've had a read of this https://github.com/LemmyNet/lemmy/pull/3725 and the post about `0.19.x` https://lemmy.world/post/5959696

It seems that we're meant to pass both the form data to ensure backwards-compatability
  > **It should be possible for clients to support both Lemmy 0.18 and 0.19 without major workarounds. If backwards compatibility is causing you trouble, comment below and we will help to find a solution.**

I suppose the issue is it means this library isn't backwards-compatible.

**Comment by dessalines** [comment]
Correct, the library is not backwards compatible. Check out an older version if you need to use that.
