### ISSUE TITLE
Exports types that aren't used

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy-js-client#200]
These types aren't used:
- PersonBlockId
- CommunityBlockId
- RegistrationApplicationResponse
- ModlogListParams
- That other ImageUpload

Should these then even be exported?

**Comment by dessalines** [comment]
If they're auto-generated I wouldn't worry about them. We could remove the `ts-rs` generations from them in the rust code if absolutely necessary.

**Comment by MV-GH** [comment]
Not necessary for me, just making aware. Incase it's sign of an issue
