### ISSUE TITLE
Generate changelogs/releases automatically

### ISSUE THREAD

**Issue by silasabbott** [LemmyNet/lemmy-js-client#213]
I'd suggest adding [changesets](https://github.com/changesets/changesets#readme) or something similar to this repo to automatically generate changelogs at each tag/release. Might be something for the backlog at this point in time, but I think this would bring more clarity and organization to the repo.

**Comment by dessalines** [comment]
What we've been doing for lemmy releases, is just showing the comparison diff, IE : https://github.com/LemmyNet/lemmy-js-client/compare/0.17.0-rc.1...0.18.0-rc.1

Having incremental changelogs probably wouldn't be as useful to app devs as seeing the side-by-side diffs like that.
