### ISSUE TITLE
Warning: punycode module is deprecated

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy-js-client#218]
I always see:

```
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Would be nice if this dependancy was updated so that the warning disappears.

**Comment by dessalines** [comment]
It looks like that's bundled with your node installation version, nothing we can control. 

https://github.com/yarnpkg/yarn/issues/9005
