### ISSUE TITLE
getSite() not returning user info

### ISSUE THREAD

**Issue by TerranFenrir** [LemmyNet/lemmy-js-client#224]
I'm developing a third party app for Lemmy while instances are upgrading to .19. The getSite() function, when passed the {auth:jwt} object returns data that contains "my_user", ie., user data. 

I'm testing on two instances: lemm.ee and sh.itjust.works. 
lemm.ee upgraded to .19 yesterday. sh.itjust.works hasn't upgraded yet. 
getSite() was fetching user data successfully prior to upgrading for lemm.ee. This is working completely fine for sh.itjust.works.

**Comment by dessalines** [comment]
auth changes are documented in the release. https://join-lemmy.org/news/2023-12-15_-_Lemmy_Release_v0.19.0_-_Instance_blocking,_Scaled_sort,_and_Federation_Queue
