### ISSUE TITLE
`exportSettings()` returns `any` instead of a concrete type

### ISSUE THREAD

**Issue by Elara6331** [LemmyNet/lemmy-js-client#229]
I've noticed that the `exportSettings()` doesn't have a concrete return type.

That causes issues for [go-lemmy](https://gitea.elara.ws/Elara6331/go-lemmy). Due to Go's statically-typed nature, it forces my code generator to decode the response into a `map[string]any` type, which is difficult for users to deal with, and breaks error handling.

It would be nice if `exportSettings()` could have a return type.

**Comment by Nutomic** [comment]
Thats because the export data shouldnt be parsed like normal api data, but stored to disk as a backup file. Maybe a `string` type would be fine?

**Comment by Elara6331** [comment]
Yeah, I think a string type would be fine, and that would also make it clearer that the intention for that endpoint is just to store it unchanged.
