### ISSUE TITLE
"uploadImage" method fails in Node.js

### ISSUE THREAD

**Issue by silasabbott** [LemmyNet/lemmy-js-client#237]
When uploading an image Buffer in Node, lemmy is returning:
```js
{
    msg: 'Multipart boundary is not found',
    files: null,
    url: undefined,
    delete_url: undefined
}
```
I think content-type headers are automatically set by fetch in the browser, but Node's fetch *does not* automatically set content-type headers and multipart boundaries when posting a form. This might be fixed by combining the headers generated by the form-data lib with user-defined headers [here](https://github.com/LemmyNet/lemmy-js-client/blob/39f247173d2e20cebc6b96b6a4ea5d47dcff6f45/src/http.ts#L1414-L1418):

```js
const response = await this.#fetchFunction(this.#pictrsUrl, {
    method: HttpType.Post,
    body: formData as unknown as BodyInit,
    headers: {
        ...this.#headers,
        ....formData.getHeaders()
    }
});
```
...or using the `formData.submit` method (although then you'd loose the custom fetch function).

Also important to note that form-data does not support File objects, so trying to upload an image File in Node throws:
```
TypeError: source.on is not a function
```

**Comment by dessalines** [comment]
You could try using https://github.com/lquixada/cross-fetch instead of node's fetch function.

If that doesn't work, could you submit a PR for this one?

**Comment by silasabbott** [comment]
`cross-fetch` worked as a workaround 🎉

Some frameworks already use custom fetch implementations for routing/caching/etc, so this solution might not work for everyone. I'll close for now, but if others are getting stuck on this we can re-open and get a permanent fix going.

**Comment by dessalines** [comment]
Sounds good.
