### ISSUE TITLE
Datatype OpenGraphData is exported but not used

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy-js-client#259]
This should be removed.

**Comment by dessalines** [comment]
Its harmless, and its auto-generated like this because in the back end we're using flatten so as not to have a breaking change. But it is its own distinct type.

```rs
pub struct LinkMetadata {
  #[serde(flatten)]
  pub opengraph_data: OpenGraphData,
  pub content_type: Option<String>,
}


```
