### ISSUE TITLE
Difference between `0.20.0-private-community.7` & `0.20.0-alpha.17`?

### ISSUE THREAD

**Issue by fishcharlie** [LemmyNet/lemmy-js-client#393]
What is the difference between `0.20.0-private-community.7` & `0.20.0-alpha.17`? Alpha makes me think it's more up to date than a feature specific tag, but the private community tags are more recent.

**Comment by dessalines** [comment]
I usually use `-alpha` or `-beta` for my feature-specific builds, but others sometimes just add the feature name explicitly. Its up to whoever is building the feature. Either way don't use these for anything production related.
