### ISSUE TITLE
browser js lib?

### ISSUE THREAD

**Issue by pwFoo** [LemmyNet/lemmy-js-client#4]
Hi, 
is it possible to use lemmy-js-client client side with a simple `<script type="text/javascript>` element? And is a detailed api documentation or swagger available?

Think about a custom html / js client with lemmy backend for some experiments.

Regards

**Comment by dessalines** [comment]
[Here's our API docs](https://lemmy.ml/docs/en/contributing/websocket_http_api.html)

[Here's some docs about creating a custom front-end](https://lemmy.ml/docs/en/contributing/custom_frontend.html), which also links `lemmy-frontend-example` showing a very simple example using this client.

**Comment by pwFoo** [comment]
Thanks @dessalines, I'm new with typescript and would prefer a simple javascript file included by script tag in html... Is it possible to use lemmy-js-client that way by generate(?) it to a js library for client side use?

**Comment by shilangyu** [comment]
With tools like skypack you can:

```html
<script type="module">
    import lemmyJsClient from "https://cdn.skypack.dev/lemmy-js-client";

    console.log(lemmyJsClient);
</script>
```
