### ISSUE TITLE
Create a common interface for http/websocket

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-js-client#59]
The apis of this library are completely separate, depending on whether you use it over http or websocket. This means any application needs to pick one or the other, and switching between them would require code changes. I think its possible to rewrite the code, so that the backend can easily be switched at runtime.

It would roughly look like this:
```
interface LemmyApi {
  async getSite(form: GetSite): Promise<GetSiteResponse>;
  async createSite(form: CreateSite): Promise<SiteResponse>;
}

class Websocket implements LemmyApi {
  ...
}

class Http implements LemmyApi {
  ...
}
```

Then the application just needs to construct either Websocket or Http class on startup depending on some conditions. For the rest of the code, it deals with LemmyApi, and doesnt need to care about the connection method at all.

**Comment by Nutomic** [comment]
So the reason this is currently not possible is because Lemmy uses a very basic protocol for websocket communication. The only fields in a message are `op` (operation type) and `data` (json request/response). But there is nothing that could indicate which request and response belong together. 

What we need to solve this problem is a higher-level protocol. The best option i found is [jsonrpc](https://github.com/paritytech/jsonrpc) and specifically the [jsonrpc-ws-server crate](https://crates.io/crates/jsonrpc-ws-server). Cause remote procedure calls are exactly what we need, and they seem to be well supported in js/ts as well. This should also allow us to clean up the code, and remove operation codes, which cant be type checked.

**Comment by dessalines** [comment]
How would this handle websocket pushes which didn't originate from your client? ie someone else creates a comment in your post room.

**Comment by Nutomic** [comment]
I dont know, maybe its possible for the server side to call RPC methods on the client. Would need investigation.

**Comment by Nutomic** [comment]
Websocket is being removed.
