### ISSUE TITLE
Make types for arguments not error when not using monads

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-js-client#90]
Suppose I want to get comments (http or websockets, it affects both).

If I'm using typescript, I need to write something like this:

```typescript
client.getComments({
    sort: CommentSortType.NEW
} as unknown as GetComments);
```

Bleck! This is necessary for many of the client functions. The issue seems to be with the `Option` monad. Even though there's logic in the class to transform the values into options where needed, typescript doesn't know about this.

Fortunately I think I know the right bit of typescript-foo to get around this with a single utility type. Expect a PR from me on this issue in the near future.

P.S. Don't let the double issue posting fool you, I love the project so much so that a Lemmy instance has become my primary stop for my social media needs. Keep up the great work!

**Comment by dessalines** [comment]
Sorry, I should have been more clear in this. You need to instantiate the type.

```ts
let commentsForm = new GetComments({
  sort: CommentSortType.NEW,
  ...
});

client.getComments(commentsForm);
```

If you're ever confused about its usage.

**Comment by SleeplessOne1917** [comment]
Thanks. I was trying to use them as plain old Typescript types. With what you just said in mind, I'll close the issue and the linked PR.
