### ISSUE TITLE
How do I keep websocket connection alive?

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-js-client#94]
This post is a question about how Lemmy's websocket connections work instead of a bug with the client.

I'm currently trying to make a bot for the instance I spend most of my time on. You can see the source code [here](https://codeberg.org/SleeplessOne1917/Lemmy-Parenti-Bot). There isn't a whole lot to it. It opens up a websocket connection, listens for posts or comments that either mention the bot or contain a specific phrase, and responds when triggered. I've got the bot to have the desired behavior, but there's a hitch: the websocket connection only stays open for about a minute or two before closing. I tried putting in logic to force the bot to reopen the connection if it was closed, but this just lead to the connection rapidly switching between open and closed until the connection failed entirely.

How do I keep the websocket connection alive indefintely?

**Comment by SleeplessOne1917** [comment]
Never mind. It turns out checking for new comments and posts every second must have triggered some rate limiting or something. It works consistently and stays nice and snappy when checking every five seconds.

**Comment by dessalines** [comment]
Don't do any polling, the point of websocket is that you don't have to. Use something like https://github.com/jjxxs/websocket-ts or another library called `reconnecting_websocket` to handle auto reconnects.
